import type { WorkAllocation } from '../types';

export type WorkAllocationView = 'ORIGINAL' | 'COPY';

/** The line that marks which version of the form this is. */
export const allocationVersionLabel = (allocation: WorkAllocation, view: WorkAllocationView) =>
  view === 'ORIGINAL' ? 'ORIGINAL — retained by the Head of Department' : `COPY — issued to ${allocation.analystName}`;

/** Rows shown in the body table, in the same order on screen and in Word. */
export const allocationRows = (allocation: WorkAllocation): [string, string][] => [
  ['Form number', allocation.formNumber],
  ['Laboratory / Section', allocation.department],
  ['Lab reference number', allocation.labReference],
  ['Exhibit / sample brought', allocation.subject || '—'],
  ['Analyst receiving', allocation.analystName],
  ['Allocated by (Head of Department)', allocation.headName],
  ['Date', allocation.allocatedAt.slice(0, 10)],
];

export const allocationFileName = (allocation: WorkAllocation, view: WorkAllocationView) =>
  `${allocation.formNumber}-${view === 'ORIGINAL' ? 'Original' : 'Copy'}.docx`;

/**
 * Builds the work allocation form as a real Word (.docx) file. The docx library
 * is loaded only when someone downloads, so it never weighs on page load.
 */
export async function buildWorkAllocationDocx(allocation: WorkAllocation, view: WorkAllocationView): Promise<Blob> {
  const {
    AlignmentType, BorderStyle, Document, Footer, Packer, Paragraph, ShadingType, Table, TableCell,
    TableRow, TextRun, WidthType,
  } = await import('docx');

  const font = 'Times New Roman';
  const text = (value: string, options: { bold?: boolean; size?: number; italics?: boolean; allCaps?: boolean } = {}) =>
    new TextRun({ text: value, font, size: options.size ?? 22, bold: options.bold, italics: options.italics, allCaps: options.allCaps });
  const centred = (runs: InstanceType<typeof TextRun>[], after = 60) =>
    new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after }, children: runs });

  const thin = { style: BorderStyle.SINGLE, size: 4, color: '808080' };
  const cellBorders = { top: thin, bottom: thin, left: thin, right: thin };

  const bodyTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: allocationRows(allocation).map(([label, value]) =>
      new TableRow({
        children: [
          new TableCell({
            width: { size: 35, type: WidthType.PERCENTAGE },
            borders: cellBorders,
            shading: { type: ShadingType.CLEAR, color: 'auto', fill: 'F2F2F2' },
            margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [text(label, { bold: true, size: 20 })] })],
          }),
          new TableCell({
            width: { size: 65, type: WidthType.PERCENTAGE },
            borders: cellBorders,
            margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [text(value, { size: 22 })] })],
          }),
        ],
      }),
    ),
  });

  const remarksBox = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            borders: cellBorders,
            margins: { top: 160, bottom: 160, left: 160, right: 160 },
            children: allocation.remarks
              .split(/\r?\n/)
              .map((line) => new Paragraph({ spacing: { after: 80 }, children: [text(line, { size: 22 })] })),
          }),
        ],
      }),
    ],
  });

  const signatureLine = (role: string, name: string) =>
    new Paragraph({
      spacing: { before: 360, after: 0 },
      children: [
        text(`${role}: `, { bold: true }),
        text(name),
        text('          Signature: ______________________          Date: ____________'),
      ],
    });

  const doc = new Document({
    creator: 'GC-ILCMS',
    title: `Work allocation form ${allocation.formNumber}`,
    description: allocationVersionLabel(allocation, view),
    sections: [
      {
        properties: {
          page: { margin: { top: 1134, bottom: 1134, left: 1134, right: 1134 } }, // 2 cm
        },
        footers: {
          default: new Footer({
            children: [
              centred(
                [text(`${allocation.formNumber} · ${allocationVersionLabel(allocation, view)} · Generated by GC-ILCMS`, { size: 16, italics: true })],
                0,
              ),
            ],
          }),
        },
        children: [
          centred([text('Republic of Kenya', { bold: true, size: 24, allCaps: true })]),
          centred([text('Ministry of Interior and National Administration', { size: 20 })]),
          centred([text('Government Chemist Department', { bold: true, size: 26 })], 40),
          centred([text(allocation.department, { size: 20 })], 240),
          centred([text('Work Allocation Form', { bold: true, size: 32, allCaps: true })], 120),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 320 },
            border: {
              top: { style: BorderStyle.SINGLE, size: 8, color: view === 'ORIGINAL' ? '047857' : '0369A1' },
              bottom: { style: BorderStyle.SINGLE, size: 8, color: view === 'ORIGINAL' ? '047857' : '0369A1' },
            },
            children: [text(allocationVersionLabel(allocation, view), { bold: true, size: 20, allCaps: true })],
          }),
          bodyTable,
          new Paragraph({ spacing: { before: 320, after: 120 }, children: [text('Remarks — work to be done', { bold: true, allCaps: true, size: 20 })] }),
          remarksBox,
          signatureLine('Allocated by (Head of Department)', allocation.headName),
          signatureLine('Received by (Analyst)', allocation.analystName),
          new Paragraph({
            spacing: { before: 480 },
            children: [
              text(
                `Issued electronically on ${allocation.allocatedAt} (Africa/Nairobi). The original is retained by the Head of Department; a copy accompanies the task issued to the analyst.`,
                { size: 18, italics: true },
              ),
            ],
          }),
        ],
      },
    ],
  });

  return Packer.toBlob(doc);
}

/** Saves a Blob to the user's downloads with the given file name. */
export function saveBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
